/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.InterfaceControl;
import Control.QuanLySanPham;
import Model.DiaNhac;
import Model.DiaPhim;
import Model.NhanVien;
import Model.Sach;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class FrameCapNhatSanPham extends javax.swing.JFrame {

    /**
     * Creates new form FrameCapNhatSanPham
     */
    private int selectIndexComboBox = 0;
    private String maSP;
    private String tenSP;
    private String loaiSP;
    private Double giaMua;
    private Double giaBan;
    private int soLuong;
    private String type;
    private String tuChon1;
    private String tuChon2;
    private String tuChon3;
    private boolean checkNumberFormat = false;
    private boolean checkNgay = false;

    private Sach s;
    private DiaNhac dn;
    private DiaPhim dp;
    private String tableName;
    private ResultSet rs;
    private FrameNhanVien frameNhanVien;
    private FrameQuanLy frameQuanLy;
    private QuanLySanPham QLSP = new QuanLySanPham();
    private NhanVien nv;
    private InterfaceControl itf;

    public FrameCapNhatSanPham(NhanVien nv, ResultSet rs, int selectIndexComboBox, String type, InterfaceControl itf) {
        initComponents();
        setLocationRelativeTo(null);
        this.selectIndexComboBox = selectIndexComboBox;
        this.itf = itf;
        this.type = type;
        this.rs = rs;
        this.nv = nv;
        comboBoxLoaiSP_ThemSP.setSelectedIndex(selectIndexComboBox);
        if (this.type.equalsIgnoreCase("UPDATE")) {
            comboBoxLoaiSP_ThemSP.setEnabled(false);
        }
        tfMaSP.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelTuChon1 = new javax.swing.JLabel();
        labelTuChon2 = new javax.swing.JLabel();
        labelTuChon3 = new javax.swing.JLabel();
        comboBoxLoaiSP_ThemSP = new javax.swing.JComboBox<>();
        tfMaSP = new javax.swing.JTextField();
        tfTenSP = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfTuChon1 = new javax.swing.JTextField();
        tfTuChon3 = new javax.swing.JTextField();
        tfTuChon2 = new javax.swing.JTextField();
        tfGiaMua = new javax.swing.JTextField();
        tfGiaBan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTheLoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btXacNhan = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật thông tin sản phẩm");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cập nhật thông tin sản phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jLabel8.setText("Giá Bán");

        jLabel6.setText("Giá Mua");

        jLabel7.setText("Tên SP");

        jLabel5.setText("Mã SP");

        jLabel4.setText("Loại SP");

        jLabel1.setText("Số lượng");

        labelTuChon1.setText("Tự chọn 1");

        labelTuChon2.setText("Tự chọn 2");

        labelTuChon3.setText("Tự chọn 3");

        comboBoxLoaiSP_ThemSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Đĩa Nhạc", "Đĩa Phim" }));
        comboBoxLoaiSP_ThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLoaiSP_ThemSPActionPerformed(evt);
            }
        });

        jLabel2.setText("Thể loại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addComponent(tfGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelTuChon1)
                    .addComponent(labelTuChon2)
                    .addComponent(labelTuChon3)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxLoaiSP_ThemSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(582, 582, 582))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(tfTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(tfTuChon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(tfTuChon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(tfTuChon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboBoxLoaiSP_ThemSP, tfGiaBan, tfGiaMua, tfMaSP, tfSoLuong, tfTenSP, tfTuChon1, tfTuChon2, tfTuChon3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel6, jLabel7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTuChon1)
                            .addComponent(tfTuChon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTuChon2)
                            .addComponent(tfTuChon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTuChon3)
                            .addComponent(tfTuChon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tfGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBoxLoaiSP_ThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)))
                .addGap(49, 49, 49))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboBoxLoaiSP_ThemSP, tfGiaBan, tfGiaMua, tfMaSP, tfSoLuong, tfTenSP, tfTuChon1, tfTuChon2, tfTuChon3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel6, jLabel7});

        btXacNhan.setText("Xác Nhận");
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        btHuy.setText("Huỷ");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btXacNhan)
                .addGap(144, 144, 144)
                .addComponent(btHuy)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btHuy, btXacNhan});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXacNhan)
                    .addComponent(btHuy))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFormAddSP(String tableName) {
        setEmptyText(); // set empty text for text feild
        tfMaSP.setText(QLSP.getMASP_FROM_TABLE(tableName));
    }

    private void loadFormUpdateSP(String tableName) {
        setEmptyText();
        tfGiaMua.setEditable(false);
        tfGiaBan.setEditable(false);
        try {
            tfMaSP.setText(rs.getString(1));
            tfTenSP.setText(rs.getString(2));
            tfTheLoai.setText(rs.getString(3));
            tfGiaMua.setText(rs.getString(4));
            tfGiaBan.setText(rs.getString(5));
            tfSoLuong.setText(rs.getString(6));
            if (tableName.equalsIgnoreCase("sach")) {
                tfTuChon1.setText(rs.getString(7).substring(0, 4));
            } else {
                tfTuChon1.setText(rs.getString(7));
            }
            tfTuChon2.setText(rs.getString(8));
            tfTuChon3.setText(rs.getString(9));
        } catch (SQLException ex) {
            Logger.getLogger(FrameCapNhatSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setEmptyText() {
        tfTenSP.setText("");
        tfTheLoai.setText("");
        tfGiaMua.setText("");
        tfGiaBan.setText("");
        tfSoLuong.setText("");
        tfTuChon1.setText("");
        tfTuChon2.setText("");
        tfTuChon3.setText("");

    }
    private void comboBoxLoaiSP_ThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLoaiSP_ThemSPActionPerformed
        selectIndexComboBox = comboBoxLoaiSP_ThemSP.getSelectedIndex();
        frameNhanVien = new FrameNhanVien(nv, selectIndexComboBox);
        frameQuanLy = new FrameQuanLy(nv, selectIndexComboBox);
        switch (selectIndexComboBox) {
            case 0:
                tableName = "sach";
                setTuChon(0);
                break;
            case 1:
                tableName = "dianhac";
                setTuChon(1);
                break;
            case 2:
                tableName = "diaphim";
                setTuChon(2);
                break;
        }
        if (this.type.equals("ADD")) {
            loadFormAddSP(tableName);
        }
        if (this.type.equals("UPDATE")) {
            loadFormUpdateSP(tableName);
        }
    }//GEN-LAST:event_comboBoxLoaiSP_ThemSPActionPerformed

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        getDataNhap();
        if (isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Thiếu thông tin!", JOptionPane.ERROR_MESSAGE);
        } else if (checkNumberFormat) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng số !", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (checkNgay) {
            if (tableName.equalsIgnoreCase("sach")) {
                JOptionPane.showMessageDialog(null, "Nhập 'Năm phát hành' theo dạng 'YYYY'", "ERROR", JOptionPane.ERROR_MESSAGE);
                tfTuChon1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Nhập 'Ngày phát hành' theo dạng 'YYYY-MM-DD'", "ERROR", JOptionPane.ERROR_MESSAGE);
                tfTuChon3.requestFocus();
            }
        } else {

            if (this.type.equalsIgnoreCase("ADD")) {
                buttonXacNhanADD();
            } else {
                buttonXacNhanUPDATE();
            }

            itf.load_ds_SP(tableName);
            itf.showSoLuong();
            
            this.dispose();
        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void buttonXacNhanUPDATE() {
        maSP = tfMaSP.getText();
        switch (selectIndexComboBox) {
            case 0:
                s = taoMoiSach();
                QLSP.CapNhatSachId(s, maSP);

                break;
            case 1:
                dn = taoMoiDiaNhac();
                QLSP.CapNhatDiaNhacId(dn, maSP);
                break;
            case 2:
                dp = taoMoiDiaPhim();
                QLSP.CapNhatDiaPhimId(dp, maSP);
                break;
        }
    }

    private void buttonXacNhanADD() {

        switch (selectIndexComboBox) {
            case 0:
                s = taoMoiSach();
                QLSP.Them_Sach(s);
                break;
            case 1:
                dn = taoMoiDiaNhac();
                QLSP.Them_DiaNhac(dn);
                break;
            case 2:
                dp = taoMoiDiaPhim();
                QLSP.Them_DiaPhim(dp);
                break;
        }
    }

    private Sach taoMoiSach() {
        Sach s = null;
        s = new Sach(convertStringToDate(tuChon1, "Year"), tuChon2, tuChon3,
                maSP, tenSP, loaiSP, giaMua, giaBan, soLuong);
        return s;
    }

    private DiaNhac taoMoiDiaNhac() {
        DiaNhac dn = null;
        dn = new DiaNhac(tuChon1, tuChon2, convertStringToDate(tuChon3, "dmy"),
                maSP, tenSP, loaiSP, giaMua, giaBan, soLuong);
        return dn;
    }

    private DiaPhim taoMoiDiaPhim() {
        DiaPhim dp = null;
        dp = new DiaPhim(tuChon1, tuChon2, tuChon3, maSP, tenSP, loaiSP, giaMua, giaBan, soLuong);
        return dp;
    }

    private boolean isEmpty() {
        boolean check = false;
        if (tfTenSP.getText().trim().equals("")
                || tfGiaMua.getText().trim().equals("")
                || tfGiaBan.getText().trim().equals("")
                || tfSoLuong.getText().trim().equals("")
                || tfTheLoai.getText().trim().equals("")
                || tfTuChon1.getText().trim().equals("")
                || tfTuChon2.getText().trim().equals("")
                || tfTuChon3.getText().trim().equals("")) {
            check = true;
        }

        return check;
    }

    private Date convertStringToDate(String dateString, String type) {
        Date date = null;
        if (type.equalsIgnoreCase("dmy")) {
            date = Date.valueOf(dateString);
        }
        if (type.equalsIgnoreCase("Year")) {
            dateString = dateString + "-1" + "-1";
            date = Date.valueOf(dateString);

        }
//        System.out.println(checkNgay);
        return date;
    }

//    private Date convertStringToDateByLocalDate(String dateString, String type) {
//        DateTimeFormatter formatter;
//        LocalDate localDate;
//        if (type.equals("Year")) {
//            formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
//            localDate = LocalDate.parse(input, formatter);
//        }
//        if (type.equals("dmy")) {
//
//        }
//        return localDate;
//    }
    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        System.out.println("Đóng Frame thêm sản phẩm");
        this.dispose();
    }//GEN-LAST:event_btHuyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Mở Frame thêm sản phẩm");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Đóng Frame thêm sản phẩm");
    }//GEN-LAST:event_formWindowClosed

    private void getDataNhap() {
        maSP = tfMaSP.getText().trim();
        tenSP = tfTenSP.getText().trim();
        loaiSP = tfTheLoai.getText().trim();
        try {
            giaMua = Double.parseDouble(tfGiaMua.getText().trim());
            giaBan = Double.parseDouble(tfGiaBan.getText().trim());
            soLuong = Integer.parseInt(tfSoLuong.getText().trim());
            checkNumberFormat = false;
        } catch (NumberFormatException e) {
            checkNumberFormat = true;
        }
        tuChon1 = tfTuChon1.getText().trim();
        tuChon2 = tfTuChon2.getText().trim();
        tuChon3 = tfTuChon3.getText().trim();

        try {
            if (tableName.equalsIgnoreCase("sach")) {
                convertStringToDate(tuChon1, "year");
            }
            if (tableName.equalsIgnoreCase("dianhac")) {
                convertStringToDate(tuChon3, "dmy");
            }
            checkNgay = false;
        } catch (IllegalArgumentException e) {
            checkNgay = true;
        }
    }

    private void setTuChon(int type) {
        switch (type) {
            case 0: {
                labelTuChon1.setText("Năm phát hành");
                labelTuChon2.setText("Tên tác giả");
                labelTuChon3.setText("Nhà XB");
            }
            break;
            case 1: {
                labelTuChon1.setText("Tên tác giá");
                labelTuChon2.setText("Ca Sĩ");
                labelTuChon3.setText("Ngày phát hành");
            }
            break;
            case 2: {
                labelTuChon1.setText("Tên đạo diễn");
                labelTuChon2.setText("Hãng SX");
                labelTuChon3.setText("Diễn viên chính");
            }
            break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCapNhatSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCapNhatSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCapNhatSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCapNhatSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JComboBox<String> comboBoxLoaiSP_ThemSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTuChon1;
    private javax.swing.JLabel labelTuChon2;
    private javax.swing.JLabel labelTuChon3;
    private javax.swing.JTextField tfGiaBan;
    private javax.swing.JTextField tfGiaMua;
    private javax.swing.JTextField tfMaSP;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenSP;
    private javax.swing.JTextField tfTheLoai;
    private javax.swing.JTextField tfTuChon1;
    private javax.swing.JTextField tfTuChon2;
    private javax.swing.JTextField tfTuChon3;
    // End of variables declaration//GEN-END:variables
private void reload() {
        if (nv.getChucVu().equalsIgnoreCase("Nhân viên")) {
            new FrameNhanVien(nv, selectIndexComboBox).setVisible(true);
        } else {
            new FrameQuanLy(nv, selectIndexComboBox).setVisible(true);
        }

    }
}
