/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ControlLogin;
import Model.NhanVien;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class FrameDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form FrameDangNhap
     */
    private String username;
    private String password;
    private ControlLogin controlLogin = new ControlLogin();
    public FrameDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        labelHienMatKhau.setText("");
        labelHienMatKhau.setVisible(false);

        //test date
        testDate();

        //set size image icon for button
        ImageIcon eye1 = new ImageIcon(getClass().getResource("eye.png"));
        Image newEye = eye1.getImage();
        newEye = newEye.getScaledInstance(50, 40, java.awt.Image.SCALE_SMOOTH);
        ImageIcon eye2 = new ImageIcon(newEye);
        btHienMatKhau.setIcon(eye2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTaiKhoan = new javax.swing.JTextField();
        pwMatKhau = new javax.swing.JPasswordField();
        btDangNhap = new javax.swing.JButton();
        btHienMatKhau = new javax.swing.JButton();
        labelHienMatKhau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cửa hàng MediaOne");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tài Khoản");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        tfTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaiKhoanActionPerformed(evt);
            }
        });
        tfTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTaiKhoanKeyTyped(evt);
            }
        });

        pwMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwMatKhauKeyTyped(evt);
            }
        });

        btDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDangNhap.setText("Đăng Nhập");
        btDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangNhapActionPerformed(evt);
            }
        });

        btHienMatKhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btHienMatKhau.setToolTipText("Hiện mật khẩu");
        btHienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHienMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btHienMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelHienMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHienMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(pwMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pwMatKhau, tfTaiKhoan});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaiKhoanActionPerformed

    private void btDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangNhapActionPerformed
        username = tfTaiKhoan.getText().trim();
        password = pwMatKhau.getText().trim();
        checkEmpty();
        checkDangNhap();


    }//GEN-LAST:event_btDangNhapActionPerformed

    private void tfTaiKhoanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTaiKhoanKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            username = tfTaiKhoan.getText().trim();
            password = pwMatKhau.getText().trim();
            if (!username.equals("") && !password.equals("")) {
                checkDangNhap();
            } else {
                checkEmpty();
            }
        }
    }//GEN-LAST:event_tfTaiKhoanKeyTyped


    private void pwMatKhauKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwMatKhauKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            username = tfTaiKhoan.getText().trim();
            password = pwMatKhau.getText().trim();
            if (!username.equals("") && !password.equals("")) {
                checkDangNhap();
            } else {
                checkEmpty();
            }
        }
    }//GEN-LAST:event_pwMatKhauKeyTyped

    private void btHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienMatKhauActionPerformed
        String hienThi = labelHienMatKhau.getText().trim();
        password = pwMatKhau.getText().trim();
        if (hienThi.equals("")) {
            pwMatKhau.setEchoChar((char) 0);
            labelHienMatKhau.setText("Da hien mat khau");
        } else {
            pwMatKhau.setEchoChar('*');
            labelHienMatKhau.setText("");
        }
    }//GEN-LAST:event_btHienMatKhauActionPerformed

    private void checkDangNhap() {
        FrameNhanVien frameNhanVien;
        FrameQuanLy frameQuanLy;
        NhanVien nv = controlLogin.chucVuTaiKhoanDangNhap(username, password);
        switch (nv.getChucVu()) {
            case "Nhân Viên":
                this.dispose();
                frameNhanVien = new FrameNhanVien(nv, 0);
                frameNhanVien.setVisible(true);
                break;
            case "Quản lý":
                this.dispose();
                frameQuanLy = new FrameQuanLy(nv,0);
                frameQuanLy.setVisible(true);
                break;
            case "":
                JOptionPane.showMessageDialog(null, "Sai tài khoản hoặc mật khẩu", "Sai tài khoản", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private void checkEmpty() {
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Thiếu thông tin", JOptionPane.INFORMATION_MESSAGE);
            if (username.equals("")) {
                tfTaiKhoan.requestFocus();
            } else {
                pwMatKhau.requestFocus();
            }
        }
    }

    private void testDate() {
        java.util.Date dateNow = new java.util.Date();
        // dateNow nhan gia tri time hien tai
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        String dateString = sdf.format(dateNow);
        System.out.println(dateString);

//        SimpleDateFormat formatDate = new SimpleDateFormat("yyyy");
//        System.out.println(formatDate.format(dateNow));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrameDangNhap.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(FrameDangNhap.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(FrameDangNhap.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(FrameDangNhap.class.getName()).log(Level.SEVERE, null, ex);
                }
                new FrameDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangNhap;
    private javax.swing.JButton btHienMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelHienMatKhau;
    private javax.swing.JPasswordField pwMatKhau;
    private javax.swing.JTextField tfTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
