/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Connect;
import Control.InterfaceControl;
import Control.QuanLySanPham;
import Model.NhanVien;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrameQuanLy extends javax.swing.JFrame implements InterfaceControl {

    /**
     * Creates new form FrameQuanLy
     */
    private DefaultTableModel model;
    private NhanVien nv;
    private FrameThongTinNhanVien nv_info;
    private FrameCapNhatSanPham CNSP;
    private int selectIndexComboBox = 0;
    private String tableName;
    private int colNumber;
    private String[] arrayData;
    private Connect con = new Connect();
    private ResultSet rs = null;
    private int selectRowTable = -1;
    private QuanLySanPham QLSP;

    public FrameQuanLy(NhanVien nv, int selectIndexComboBox) {
        initComponents();
        System.out.println("Frame Quản lý");
        setLocationRelativeTo(null);

        this.nv = nv;
        this.selectIndexComboBox = selectIndexComboBox;
        comboBoxLoaiSP.setSelectedIndex(selectIndexComboBox);

        if (nv != null) {
            menuHello.setText("Xin chào " + nv.getTenNV());
        }

        // connect database
        con.connect();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        tfGT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfSL_Sach = new javax.swing.JTextField();
        tfSL_DiaNhac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxLoaiSP = new javax.swing.JComboBox<>();
        tfSL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfSL_DiaPhim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfTimKiem = new javax.swing.JTextField();
        comboBoxTimKiem = new javax.swing.JComboBox<>();
        btCapNhat = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHello = new javax.swing.JMenu();
        menuItemAccountInfo = new javax.swing.JMenuItem();
        menuItemDangXua = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện Quản lý");

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Loại SP", "Giá Mua", "Giá Bán", "Số lượng", "Tự chọn 1", "Tự chọn 2", "Tự chọn 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jLabel2.setText("Loại SP");

        jLabel5.setText("Đĩa Phim");

        jLabel6.setText("Tổng số lượng");

        comboBoxLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Đĩa Nhạc", "Đĩa Phim" }));
        comboBoxLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLoaiSPActionPerformed(evt);
            }
        });

        jLabel7.setText("Tổng giá trị bán ra");

        jLabel4.setText("Đĩa Nhạc");

        jLabel3.setText("Sách");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfSL, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSL_DiaPhim, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSL_DiaNhac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSL_Sach, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxLoaiSP, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                    .addComponent(tfGT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSL_Sach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSL_DiaNhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSL_DiaPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        comboBoxTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btCapNhat.setText("Cập nhật");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setText("Xoá");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btThem)
                .addGap(129, 129, 129)
                .addComponent(btCapNhat)
                .addGap(142, 142, 142)
                .addComponent(btXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboBoxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btTimKiem))
                .addGap(73, 73, 73))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCapNhat, btThem, btTimKiem, btXoa});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btTimKiem)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btCapNhat)
                    .addComponent(btXoa)
                    .addComponent(comboBoxTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý sản phẩm", jPanel1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý nhân viên", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý hoá đơn", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thống kê", jPanel8);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cửa hàng MediaOne");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        menuHello.setText("Xin chào..........");

        menuItemAccountInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAccountInfo.setText("Thông tin tài khoản");
        menuItemAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAccountInfoActionPerformed(evt);
            }
        });
        menuHello.add(menuItemAccountInfo);

        menuItemDangXua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuItemDangXua.setText("Đăng xuất");
        menuItemDangXua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangXuaActionPerformed(evt);
            }
        });
        menuHello.add(menuItemDangXua);

        jMenuBar1.add(menuHello);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLoaiSPActionPerformed
        selectIndexComboBox = comboBoxLoaiSP.getSelectedIndex();
        showSoLuong();
        switch (selectIndexComboBox) {
            case 0:
                tableName = "sach";
                this.load_ds_SP(tableName);
                break;
            case 1:
                tableName = "dianhac";
                this.load_ds_SP(tableName);
                break;
            case 2:
                tableName = "diaphim";
                this.load_ds_SP(tableName);
                break;
        }
    }//GEN-LAST:event_comboBoxLoaiSPActionPerformed

    private void menuItemAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAccountInfoActionPerformed
        if (nv != null) {
//            this.dispose();
            nv_info = new FrameThongTinNhanVien(nv);
            nv_info.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Bạn đăng nhập với tư cách khách !", "Lỗi tài khoản", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemAccountInfoActionPerformed

    private void menuItemDangXuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangXuaActionPerformed
        this.dispose();
        new FrameDangNhap().setVisible(true);
    }//GEN-LAST:event_menuItemDangXuaActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        rs = null;
        CNSP = new FrameCapNhatSanPham(nv, rs, selectIndexComboBox, "ADD", this);
        CNSP.setVisible(true);

    }//GEN-LAST:event_btThemActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        if (selectRowTable < 0) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn sản phẩm để cập nhật !", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String maSP = tableSanPham.getValueAt(selectRowTable, 1).toString();

            // lay rs tu quan ly san pham
            QLSP = new QuanLySanPham();
            rs = QLSP.getDataSPId(tableName, maSP);
            try {
                rs.next(); //goi toi rs.next()
            } catch (SQLException ex) {
                Logger.getLogger(FrameQuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }

            // goi toi cap nhat san pham
            CNSP = new FrameCapNhatSanPham(nv, rs, selectIndexComboBox, "UPDATE", this);
//            this.dispose();
            CNSP.setVisible(true);
        }
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        selectRowTable = tableSanPham.getSelectedRow();


    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if (selectRowTable < 0) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn 1 sản phẩm để xoá !", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String maSP = tableSanPham.getValueAt(selectRowTable, 1).toString();
            int option = JOptionPane.showConfirmDialog(null, "Bạn muốn xoá sản phẩm " + maSP + " !", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                QLSP = new QuanLySanPham();
                QLSP.XoaId(tableName, maSP);
                comboBoxLoaiSP.setSelectedIndex(selectIndexComboBox);
            } else {
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameQuanLy(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> comboBoxLoaiSP;
    private javax.swing.JComboBox<String> comboBoxTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuHello;
    private javax.swing.JMenuItem menuItemAccountInfo;
    private javax.swing.JMenuItem menuItemDangXua;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField tfGT;
    private javax.swing.JTextField tfSL;
    private javax.swing.JTextField tfSL_DiaNhac;
    private javax.swing.JTextField tfSL_DiaPhim;
    private javax.swing.JTextField tfSL_Sach;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables

    public void tao_arrayData(ResultSet rs) {
//        System.out.println("Tao array");
        try {
            // de co the lay ten cot trong bang va so cot trong bang
            ResultSetMetaData rsMD = rs.getMetaData();

            // lay so cot
            colNumber = rsMD.getColumnCount();

            //tao mang moi co colNumber chieu, tinh ca cot STT
            arrayData = new String[colNumber + 1];

        } catch (SQLException ex) {
            Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void load_ds_SP(String tableName) {
        model = (DefaultTableModel) tableSanPham.getModel();
        model.setRowCount(0);
        con.connect();
        int STT = 0;
        //lay data
        rs = con.getData(tableName);
        System.out.println("Load Data Table");

        // tao mang 
        tao_arrayData(rs);

        try {
            while (rs.next()) {
//                System.out.println(rs.getString(2));
                STT++;
                arrayData[0] = String.valueOf(STT);
                for (int i = 0; i < colNumber; i++) {
                    arrayData[i + 1] = rs.getString(i + 1);
                }
                model.addRow(arrayData);

                //test debug
//                System.out.println(arrayData[3]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void load_ds_sach() {
    }

    @Override
    public void load_ds_diaPhim() {
    }

    @Override
    public void load_ds_diaNhac() {
    }

    @Override
    public void showSoLuong() {
        setEditableText(false);

        QLSP = new QuanLySanPham();
        int SL_Sach = QLSP.getSoLuongSP("sach");
        int SL_DiaNhac = QLSP.getSoLuongSP("dianhac");
        int SL_DiaPhim = QLSP.getSoLuongSP("diaphim");
        
        double GT_Sach = QLSP.getGiaTriSP("sach");
        double GT_DiaNhac = QLSP.getGiaTriSP("dianhac");
        double GT_DiaPhim = QLSP.getGiaTriSP("diaphim");
        
        double tongGT = GT_Sach + GT_DiaNhac + GT_DiaPhim;
        int tongSL = SL_Sach + SL_DiaNhac + SL_DiaPhim;
 
        tfSL_Sach.setText(String.valueOf(SL_Sach));
        tfSL_DiaNhac.setText(String.valueOf(SL_DiaNhac));
        tfSL_DiaPhim.setText(String.valueOf(SL_DiaPhim));
        tfSL.setText(String.valueOf(tongSL));
        
        tfGT.setText(QLSP.convertDoubleToStringWithFormat(tongGT));
    }

    public void setEditableText(boolean check) {
        tfSL_Sach.setEditable(check);
        tfSL_DiaNhac.setEditable(check);
        tfSL_DiaPhim.setEditable(check);
        tfSL.setEditable(check);
        tfGT.setEditable(check);
    }
}
